name: cml

on:
    push:
jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - uses: iterative/setup-cml@v1
      - name: Install package
        run: |
          uv sync --all-extras --dev
      - name: Run pytest
        run: |
          uv run python --version
          uv run pytest --benchmark-histogram benchmark -m benchmark
          uv run python benchmarks/read.py
      - name: Create report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo '# Benchmark' >> report.md
          echo '## Write: Varying number of images' >> report.md
          echo '![](./benchmark-write-count.svg "Write benchmark, varying count")' >> report.md
          echo '## Write: Varying number of atoms' >> report.md
          echo '![](./benchmark-write-size.svg "Write benchmark, varying size")' >> report.md

          echo '## Read: Varying number of images' >> report.md
          echo '![](./benchmark-read-count.svg "Read benchmark, varying count")' >> report.md
          echo '## Read: Varying number of atoms' >> report.md
          echo '![](./benchmark-read-size.svg "Read benchmark, varying size")' >> report.md

          echo '## Read: Comparison with other packages' >> report.md
          echo '![](./benchmark_h5md.png "Read benchmark, comparison with other packages")' >> report.md
          echo '![](./benchmark_h5md-uncompressed.png "Read benchmark, comparison with other packages")' >> report.md
          echo '![](./benchmark_xyz.png "Read benchmark, comparison with other packages")' >> report.md
          echo '![](./benchmark_pdb.png "Read benchmark, comparison with other packages")' >> report.md
          echo '![](./benchmark_xtc.png "Read benchmark, comparison with other packages")' >> report.md

          cml comment update report.md
