name: cml

on:
    push:
jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: iterative/setup-cml@v1
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install package
        run: |
          poetry install --no-interaction
      - name: Run pytest
        run: |
          poetry run python --version
          poetry run pytest --benchmark-histogram benchmark -m benchmark
      - name: Create report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo '# Benchmark' >> report.md
          echo '## READ' >> report.md
          echo '![](./benchmark-write.svg "Write benchmark")' >> report.md
          echo '![](./benchmark-read.svg "Read benchmark")' >> report.md
          cat report.md
          ls -la
          cml comment create report.md
